pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_ENOUGH_BALANCE: u32 = 3;
pub const ERROR_INDEX_OUT_OF_BOUND: u32 = 4;
pub const ERROR_NOT_ENOUGH_RESOURCE: u32 = 5;
